name: Google Drive Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create credentials file
      env:
        GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}
      run: |
        echo "$GDRIVE_CREDENTIALS_JSON" > credentials.json

    - name: Run script
      run: |
        streamlit run main.py  # Reemplaza "VentaPerdida.py" con el nombre de tu script si es diferente
